export function getRandomQuote(quotes: string[]): string {
  const randomIndex = Math.floor(Math.random() * quotes.length);
  return quotes[randomIndex];
}

export const quotes: string[] = [
  'The unexamined life is not worth living. – Socrates',
  'Happiness is not an ideal of reason but of imagination. – Immanuel Kant',
  'Man is condemned to be free; because once thrown into the world, he is responsible for everything he does. – Jean-Paul Sartre',
  'The only true wisdom is in knowing you know nothing. – Socrates',
  'You must be the change you wish to see in the world. – Mahatma Gandhi',
  'I think, therefore I am. – René Descartes',
  'He who has a why to live can bear almost any how. – Friedrich Nietzsche',
  'No great mind has ever existed without a touch of madness. – Aristotle',
  'Freedom is the power to choose our own chains. – Jean-Jacques Rousseau',
  'We are what we repeatedly do. Excellence, then, is not an act, but a habit. – Aristotle',
  'To be is to be perceived. – George Berkeley',
  'The mind is furnished with ideas by experience alone. – John Locke',
  'We do not see things as they are, we see them as we are. – Anaïs Nin',
  'Life must be understood backward. But it must be lived forward. – Søren Kierkegaard',
  'Hell is other people. – Jean-Paul Sartre',
  'He who controls others may be powerful, but he who has mastered himself is mightier still. – Lao Tzu',
  'That which does not kill us makes us stronger. – Friedrich Nietzsche',
  'Man is the only creature who refuses to be what he is. – Albert Camus',
  'The greatest wealth is to live content with little. – Plato',
  'We are what we pretend to be, so we must be careful about what we pretend to be. – Kurt Vonnegut',
  'It is not length of life, but depth of life. – Ralph Waldo Emerson',
  'The only way to deal with fear is to face it head-on. – Carl Jung',
  'The only journey is the one within. – Rainer Maria Rilke',
  "I have not failed. I've just found 10,000 ways that won't work. – Thomas Edison",
  'It is the mark of an educated mind to be able to entertain a thought without accepting it. – Aristotle',
  'Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. – Buddha',
  'There is only one way to avoid criticism: do nothing, say nothing, and be nothing. – Aristotle',
  'Act as if what you do makes a difference. It does. – William James',
  'The happiness of your life depends upon the quality of your thoughts. – Marcus Aurelius',
  'Knowing others is intelligence; knowing yourself is true wisdom. – Lao Tzu',
  'The pendulum of the mind oscillates between sense and nonsense, not between right and wrong. – Carl Jung',
  'It is better to be hated for what you are than to be loved for what you are not. – André Gide',
  'To love is to find pleasure in the happiness of others. – Gottfried Leibniz',
  'The purpose of life is to live it, to taste experience to the utmost, to reach out eagerly and without fear for newer and richer experience. – Eleanor Roosevelt',
  'Wisdom is not a product of schooling but of the lifelong attempt to acquire it. – Albert Einstein',
  'In the depth of winter, I finally learned that within me there lay an invincible summer. – Albert Camus',
  'I am not what happened to me, I am what I choose to become. – Carl Jung',
  'Education is the kindling of a flame, not the filling of a vessel. – Socrates',
  'When we are no longer able to change a situation, we are challenged to change ourselves. – Viktor Frankl',
  'Happiness depends upon ourselves. – Aristotle',
  'He who knows, does not speak. He who speaks, does not know. – Lao Tzu',
  'Whereof one cannot speak, thereof one must be silent. – Ludwig Wittgenstein',
  'Man is nothing else but what he makes of himself. – Jean-Paul Sartre',
  'It is during our darkest moments that we must focus to see the light. – Aristotle',
  'The curious paradox is that when I accept myself just as I am, then I can change. – Carl Rogers',
  'A life spent making mistakes is not only more honorable but more useful than a life spent doing nothing. – George Bernard Shaw',
  'Your vision will become clear only when you look into your heart. Who looks outside, dreams; who looks inside, awakes. – Carl Jung',
  'Man is the measure of all things. – Protagoras',
  'To live is to suffer, to survive is to find some meaning in the suffering. – Friedrich Nietzsche',
  'The way to do is to be. – Lao Tzu',
  'The privilege of a lifetime is to become who you truly are. – Carl Jung',
  'Injustice anywhere is a threat to justice everywhere. – Martin Luther King Jr.',
  'You can discover more about a person in an hour of play than in a year of conversation. – Plato',
  'The greatest glory in living lies not in never falling, but in rising every time we fall. – Nelson Mandela',
  'We are more often frightened than hurt; and we suffer more from imagination than from reality. – Seneca',
  'We live in the best of all possible worlds. – Gottfried Leibniz',
  'I have no special talent. I am only passionately curious. – Albert Einstein',
  'It is one thing to show a man that he is in error, and another to put him in possession of truth. – John Locke',
  'The desire for safety stands against every great and noble enterprise. – Tacitus',
  'Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson',
  'Men are disturbed not by things, but by the view which they take of them. – Epictetus',
  "Everything can be taken from a man but one thing: the last of the human freedoms – to choose one's attitude in any given set of circumstances, to choose one's own way. – Viktor Frankl",
  'The soul becomes dyed with the color of its thoughts. – Marcus Aurelius',
  'Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill',
  'The mind is everything. What you think you become. – Buddha',
  'One cannot step twice in the same river. – Heraclitus',
  'It is not what happens to you, but how you react to it that matters. – Epictetus',
  'Life itself is the most wonderful fairy tale. – Hans Christian Andersen',
  'There are two ways to live: you can live as if nothing is a miracle; you can live as if everything is a miracle. – Albert Einstein',
  'The weak can never forgive. Forgiveness is the attribute of the strong. – Mahatma Gandhi',
  'All that we see or seem is but a dream within a dream. – Edgar Allan Poe',
  'Happiness is not something ready-made. It comes from your own actions. – Dalai Lama',
  'When you arise in the morning, think of what a precious privilege it is to be alive – to breathe, to think, to enjoy, to love. – Marcus Aurelius',
  'The aim of art is to represent not the outward appearance of things, but their inward significance. – Aristotle',
  'I am always doing that which I cannot do, in order that I may learn how to do it. – Pablo Picasso',
  'The most beautiful experience we can have is the mysterious. – Albert Einstein',
  'What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson',
  'No man is free who is not master of himself. – Epictetus',
  'The whole is greater than the sum of its parts. – Aristotle',
  'One must still have chaos in oneself to be able to give birth to a dancing star. – Friedrich Nietzsche',
  'Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau',
  'The important thing is not to stop questioning. Curiosity has its own reason for existence. – Albert Einstein',
  'There are no facts, only interpretations. – Friedrich Nietzsche',
  'The purpose of psychology is to give us a completely different idea of the things we know best. – Paul Valéry',
  'Love is composed of a single soul inhabiting two bodies. – Aristotle',
  'Tell me and I forget. Teach me and I remember. Involve me and I learn. – Benjamin Franklin',
  'I would rather die of passion than of boredom. – Vincent van Gogh',
  'The more sand that has escaped from the hourglass of our life, the clearer we should see through it. – Jean-Paul Sartre',
];
